// Auto-generated by sdkgen
const { Contract } = require("quantumcoin");

/**
 * IERC20 - A typed contract interface for IERC20
 */
class IERC20 extends Contract {
  static abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "spender",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "Approval",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "Transfer",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "spender",
        "type": "address"
      }
    ],
    "name": "allowance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "spender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "approve",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "name",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "symbol",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalSupply",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "transfer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "transferFrom",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
];
  static bytecode = "0x";

  static connect(address, runner) {
    return new IERC20(address, runner);
  }

  constructor(address, runner, _deployTx) {
    super(address, IERC20.abi, runner, IERC20.bytecode);
    this._deployTx = _deployTx;

    // Typed populateTransaction helpers (offline signing / sendRawTransaction flows)
    this.populateTransaction = {
      approve: async (spender, value, overrides) => {
        const data = this.interface.encodeFunctionData("approve", [spender, value]);
        const safeOverrides = {};
        for (const k of ["value", "gasLimit", "gasPrice", "maxFeePerGas", "maxPriorityFeePerGas", "nonce", "chainId", "remarks", "signingContext"]) { if (overrides && overrides[k] !== undefined) safeOverrides[k] = overrides[k]; }
        return { ...safeOverrides, to: this.address, data };
      },
      transfer: async (to, value, overrides) => {
        const data = this.interface.encodeFunctionData("transfer", [to, value]);
        const safeOverrides = {};
        for (const k of ["value", "gasLimit", "gasPrice", "maxFeePerGas", "maxPriorityFeePerGas", "nonce", "chainId", "remarks", "signingContext"]) { if (overrides && overrides[k] !== undefined) safeOverrides[k] = overrides[k]; }
        return { ...safeOverrides, to: this.address, data };
      },
      transferFrom: async (from, to, value, overrides) => {
        const data = this.interface.encodeFunctionData("transferFrom", [from, to, value]);
        const safeOverrides = {};
        for (const k of ["value", "gasLimit", "gasPrice", "maxFeePerGas", "maxPriorityFeePerGas", "nonce", "chainId", "remarks", "signingContext"]) { if (overrides && overrides[k] !== undefined) safeOverrides[k] = overrides[k]; }
        return { ...safeOverrides, to: this.address, data };
      },
    };
  }

  /**
   * allowance
   * @param {import("quantumcoin/types").AddressLike} owner
   * @param {import("quantumcoin/types").AddressLike} spender
   * @returns {Promise<import("quantumcoin/types").Uint256>} 
   */
  async allowance(owner, spender) {
    const res = await this.call("allowance", [owner, spender]);
    return Array.isArray(res) ? res[0] : res;
  }

  /**
   * approve
   * @param {import("quantumcoin/types").AddressLike} spender
   * @param {import("quantumcoin/types").Uint256Like} value
   * @returns {Promise<import("quantumcoin").ContractTransactionResponse>}
   */
  async approve(spender, value, overrides) {
    return this.send("approve", [spender, value], overrides);
  }

  /**
   * balanceOf
   * @param {import("quantumcoin/types").AddressLike} owner
   * @returns {Promise<import("quantumcoin/types").Uint256>} 
   */
  async balanceOf(owner) {
    const res = await this.call("balanceOf", [owner]);
    return Array.isArray(res) ? res[0] : res;
  }

  /**
   * decimals
   * @returns {Promise<import("quantumcoin/types").Uint8>} 
   */
  async decimals() {
    const res = await this.call("decimals", []);
    return Array.isArray(res) ? res[0] : res;
  }

  /**
   * name
   * @returns {Promise<string>} 
   */
  async name() {
    const res = await this.call("name", []);
    return Array.isArray(res) ? res[0] : res;
  }

  /**
   * symbol
   * @returns {Promise<string>} 
   */
  async symbol() {
    const res = await this.call("symbol", []);
    return Array.isArray(res) ? res[0] : res;
  }

  /**
   * totalSupply
   * @returns {Promise<import("quantumcoin/types").Uint256>} 
   */
  async totalSupply() {
    const res = await this.call("totalSupply", []);
    return Array.isArray(res) ? res[0] : res;
  }

  /**
   * transfer
   * @param {import("quantumcoin/types").AddressLike} to
   * @param {import("quantumcoin/types").Uint256Like} value
   * @returns {Promise<import("quantumcoin").ContractTransactionResponse>}
   */
  async transfer(to, value, overrides) {
    return this.send("transfer", [to, value], overrides);
  }

  /**
   * transferFrom
   * @param {import("quantumcoin/types").AddressLike} from
   * @param {import("quantumcoin/types").AddressLike} to
   * @param {import("quantumcoin/types").Uint256Like} value
   * @returns {Promise<import("quantumcoin").ContractTransactionResponse>}
   */
  async transferFrom(from, to, value, overrides) {
    return this.send("transferFrom", [from, to, value], overrides);
  }
}

module.exports = { IERC20 };
