// Auto-generated by sdkgen
const { ContractFactory, getCreateAddress } = require("quantumcoin");
const { QuantumSwapV2Factory } = require("./QuantumSwapV2Factory");

class QuantumSwapV2Factory__factory extends ContractFactory {
  constructor(runner) {
    super(QuantumSwapV2Factory.abi, QuantumSwapV2Factory.bytecode, runner);
  }

  async deploy(_feeToSetter, overrides) {
    const signer = this.signer;
    if (!signer) { throw new Error("missing signer"); }
    const from = signer.getAddress ? await signer.getAddress() : signer.address;
    const provider = signer.provider;
    if (!provider || !provider.getTransactionCount) { throw new Error("missing provider"); }
    let nonce;
    try { nonce = await provider.getTransactionCount(from, "pending"); } catch { nonce = await provider.getTransactionCount(from, "latest"); }
    const address = getCreateAddress({ from, nonce });
    const txReq = this.getDeployTransaction(_feeToSetter);
    const safeOverrides = {};
    for (const k of ["value", "gasLimit", "gasPrice", "maxFeePerGas", "maxPriorityFeePerGas", "remarks", "signingContext"]) { if (overrides && overrides[k] !== undefined) safeOverrides[k] = overrides[k]; }
    const tx = await signer.sendTransaction({ ...txReq, ...safeOverrides, nonce });
    return new QuantumSwapV2Factory(address, signer, tx);
  }

  static connect(address, runner) {
    return QuantumSwapV2Factory.connect(address, runner);
  }
}

module.exports = { QuantumSwapV2Factory__factory };
