// Auto-generated by sdkgen
const { ContractFactory, getCreateAddress } = require("quantumcoin");
const { QuantumSwapV2ERC20 } = require("./QuantumSwapV2ERC20");

class QuantumSwapV2ERC20__factory extends ContractFactory {
  constructor(runner) {
    super(QuantumSwapV2ERC20.abi, QuantumSwapV2ERC20.bytecode, runner);
  }

  async deploy(overrides) {
    const signer = this.signer;
    if (!signer) { throw new Error("missing signer"); }
    const from = signer.getAddress ? await signer.getAddress() : signer.address;
    const provider = signer.provider;
    if (!provider || !provider.getTransactionCount) { throw new Error("missing provider"); }
    let nonce;
    try { nonce = await provider.getTransactionCount(from, "pending"); } catch { nonce = await provider.getTransactionCount(from, "latest"); }
    const address = getCreateAddress({ from, nonce });
    const txReq = this.getDeployTransaction();
    const safeOverrides = {};
    for (const k of ["value", "gasLimit", "gasPrice", "maxFeePerGas", "maxPriorityFeePerGas", "remarks", "signingContext"]) { if (overrides && overrides[k] !== undefined) safeOverrides[k] = overrides[k]; }
    const tx = await signer.sendTransaction({ ...txReq, ...safeOverrides, nonce });
    return new QuantumSwapV2ERC20(address, signer, tx);
  }

  static connect(address, runner) {
    return QuantumSwapV2ERC20.connect(address, runner);
  }
}

module.exports = { QuantumSwapV2ERC20__factory };
